### ISSUE TITLE
Trouble with templates on iPhone and iPad

### ISSUE THREAD

**Issue by surfer-09** [PhiTux/DailyTxT#30] opened 2023-04-19 19:13 UTC
It's me again ;-)
I've noticed that the template selection doesn't work properly on iPhone and iPad. In my example I have selected template 2 but text of template 3 is being written. If you select the last template, nothing happens at all.

![Auswahl](https://user-images.githubusercontent.com/106930606/233175985-1634c1a3-9ccc-4544-9153-022809f1c304.jpg)

![Baustein_2](https://user-images.githubusercontent.com/106930606/233175968-b2601051-4c4e-4ca0-9d2a-d5deb905cd75.jpg)

At first I thought I had created the templates incorrectly and created them again. I also cleaned the browser cache on the devices but the problem persisted.
On PC the templates worked fine.

Greetings :-)

**Comment by PhiTux** [comment] 2023-04-20 06:13
Thanks!
That definitely looks like a bug or something by apple!

I've got an iPad and just tested it. I can confirm this bug with opera on iPad but NOT with safari on iPad. 
Which browser do you use?

**Comment by PhiTux** [comment] 2023-07-13 18:31
Fixed in 1.0.13

**Closed by PhiTux** 2023-07-13 18:31 UTC
Labels: bug
