### ISSUE TITLE
New installation fails with latest (1.14.0) container-tag

### ISSUE THREAD

**Issue by Husky110** [PhiTux/DailyTxT#45] opened 2024-06-08 07:26 UTC
Hi,  
When you try to install a new instance of DailyTXT the container crashes on startup with a message stating: `syntax error: Unexpected (`. This happens when you add the PORT-env-variable. Without that it fails with another message. Once you use the old 1.13.0-tag for setup and switch to the latest-tag then, it works.  
Greetings

**Comment by Stokkie64** [comment] 2024-06-08 12:05
HI!
Thanks for logging your issue. 

Can you post your `docker-compose.yml `? Without passwords in. 
I suspect there's a simple syntax error. As this does not occur for me.  If that does not appear to be the issue we can look further into steps to reproduce it.

Alternatively you can copy paste it to an online validator.

**Comment by Husky110** [comment] 2024-06-08 20:51
@Stokkie64 - I do not use a docker-compose.yml, since I've set up the container within portainer.  
The container runs as standalone with those env-parameters:
```
TZ="Europe/Berlin"
GOTIFY_SERVER_PORT=80
GOTIFY_SERVER_SSL_ENABLED=false
```
By the way - the issue still persists - I still see that error in my container notifications.

**Comment by PhiTux** [comment] 2024-06-08 21:01
Hey, 

@Husky110 - sorry to hear that!
@Stokkie64 - thanks for your help! I also suspect a syntax error - in this case probably somewhere in your portainer-configuration?

I have absolutely no experience with portainer, but you need to set a few environment variables! Look at the "installation" section in the readme, there are several env-vars explained. A few of those are necessary, especially the port-variable (not to be confused with the separate port-setting that you need on pretty every docker-container).

**Comment by Husky110** [comment] 2024-06-09 08:33
Hey @PhiTux,

Portainer is just basic docker-commands with a nice gui. You should be able to replicate the issue by just running this in your terminal: `docker run -e ALLOW_REGISTRATION=false -e PORT=8765 phitux/dailytxt:latest"  
I just realized that I posted the wrong env-variables before - fixed that. Please check again.

**Comment by PhiTux** [comment] 2024-06-09 08:44
Your command is incomplete.
You need the port-setting (as I said, not to be confused with the env-var).
This works for me: `docker run -p 8765:8765 -e ALLOW_REGISTRATION=false -e PORT=8765 phitux/dailytxt:latest`
But you will also need to mount a volume for consistent data storage!

**Comment by Husky110** [comment] 2024-06-09 10:06
Yes, but that should have nothing to do with the issue.

**Comment by PhiTux** [comment] 2024-06-09 10:09
Well, still I can absolutely not reproduce your issue! Do you have the possibility to test it on another system without portainer and use the `docker run` command? 
I just checked it on a separate machine where dailytxt was never running before, and it just worked!

**Comment by Husky110** [comment] 2024-06-09 10:24
Hmm - I tried it on my rootfull-docker-instance and it works... Could this be a docker rootless-issue?

**Comment by PhiTux** [comment] 2024-06-09 10:28
That could perhaps be the reason, yes. But I cannot really evaluate this, as I'm not aware enough about the differences of rootful/rootless docker. Normally I would guess that dailytxt doesn't work in such a way, that it makes a difference if it's root or not.

**Comment by Husky110** [comment] 2024-06-09 10:42
Hmm - I don't get it... Tried it with rootless docker again on my other machine and it works... Maybe it has something to do with portainer...  
Here is what I set:  
Basis:  
![image](https://github.com/PhiTux/DailyTxT/assets/13180625/8065e750-cada-4ab7-b96d-ecae56c9d3d9)

Volume:  
![image](https://github.com/PhiTux/DailyTxT/assets/13180625/a6c19c4e-d343-4fff-b0e2-31c16118a47d)

And env-varibles (note: some of them are set automatically):
![image](https://github.com/PhiTux/DailyTxT/assets/13180625/284542ea-da9c-40d8-b3e9-5a5ec846f94b)

And I still see this:  
![image](https://github.com/PhiTux/DailyTxT/assets/13180625/3fc96cd3-a787-4397-9679-feebbe58f836)

**Comment by PhiTux** [comment] 2024-06-09 10:46
Thanks for the images!
Why do you set all those Python-Env-variables, like python_version? I can imagine, that this 'confuses' dailytxt, as it uses python itself in the backend. Wrong env-vars might lead to wrong code-interpretation

**Comment by Husky110** [comment] 2024-06-09 10:49
I am not sure if Docker or Portainer does it itself.  
I started that with only Allow_Registration and Port - and nothing else.  
If you got Discord I can show you...

**Comment by PhiTux** [comment] 2024-06-09 10:50
Docker doesn't set those variables. That must be portainer! Can you just delete them?

**Comment by Husky110** [comment] 2024-06-09 10:52
Yep - but they will straight away come back, since those are env-variables within the system itself and portainer allows to change them.

**Comment by PhiTux** [comment] 2024-06-09 10:57
Okay I see, so those are the variables that are generated within the container and portainer keeps track of them...

Well, then I'm actually out of ideas... I don't see anything strange in the other settings Perhaps @Stokkie64 has some idea?

I will close the issue by now, as it doesn't seem to be a dailytxt-error. But feel free to continue asking, if you have other ideas or information.

**Closed by PhiTux** 2024-06-09 10:57 UTC

**Comment by Stokkie64** [comment] 2024-06-09 11:21
I do have portainer running in my homelab so will try to have a look and see if I can reproduce the error. 

But that will only be tomorrow/later this week as I'm not home at the moment. Will report back on this thread!
